### ISSUE TITLE
wrong parameter format for find in makefile

### ISSUE THREAD

**Issue by ghost** [cambridgehackers/zynq-boot-filesystems#1]
The makefile gives an error message for 'find' : Parameter format not correct. 

A search suggested to use quotation marks on parameter of find. I don't understand the script, however

Error message: 

D:\RePos\zynq-boot>make all.zybo
make BOARD=zybo real.all
make[1]: Entering directory `D:/RePos/zynq-boot'
gcc -o canoncpio canoncpio.c
chmod 644 data/*.rc data/*.prop
cd data; (find . -name unused -o -print | sort | cpio -H newc -o >../ramdisk.ima
ge.temp1)
FIND: Parameterformat falsch
/usr/bin/sh: cpio: command not found
make[1]: *** [ramdisk] Error 127
make[1]: Leaving directory `D:/RePos/zynq-boot'
make: *** [all.zybo] Error 2

D:\RePos\zynq-boot>

**Comment by jameyhicks** [comment]
It looks like the actual problem is that /usr/bin/sh could not find the cpio executable.
